@startuml ClassDiagram
package "ca.mcmaster.se2aa4.mazerunner" {
    enum Direction {
        UP
        DOWN
        LEFT
        RIGHT
    }

    class Node {
        Node root
        Node R
        Node L
        Node M
    }

    class Position {
        x: int
        y: int
        
    }

    class Path {
        
    }
    
    class MazeBFSSolver{

    } 
    
    class Main{
        -load(args:String)
    }

    interface MazeSolver{
        +solve()
    }

    class RightHandSolver{

    }
    
    class TremauxSolver{

    }

    package "ca.mcmaster.se2aa4.mazerunner.Factory" {
        interface MazeExplorer {
            +runs(): Maze
        }

        class Benchmarking {
        
        }   

        class PathCalculator {
        
        }

        class PathValidation{

        }

        class Maze {
        
        -start: Position
        -end: Position
        
        }

    }
}



Benchmarking ..|> MazeExplorer
PathCalculator ..|> MazeExplorer
PathValidation ..|> MazeExplorer

PathCalculator --> MazeSolver

TremauxSolver --> Path


Benchmarking --> MazeSolver

MazeBFSSolver ..|> MazeSolver
RightHandSolver ..|> MazeSolver
TremauxSolver ..|> MazeSolver

MazeExplorer *--> Maze

Main o--> Maze
Main o--> MazeExplorer
Main *--> Benchmarking
Main *--> PathCalculator
Main *--> PathValidation


MazeBFSSolver o--> Maze
MazeBFSSolver --> Node
MazeBFSSolver --> Path
MazeBFSSolver --> Direction
MazeBFSSolver --> Position

Node o--> Position

Position *--> Direction

RightHandSolver *--> Path
RightHandSolver o--> Direction
RightHandSolver o--> Position

TremauxSolver o--> Direction
TremauxSolver o--> Position


@enduml