@startuml SequenceDiagram

participant Main
participant MazeExplorer
participant MazeSolver


activate Main

alt 
Main -> MazeExplorer: Benchmarking("method", "baseline")
activate MazeExplorer
Main <-- MazeExplorer
else
Main -> MazeExplorer: PathCalculator(cmd)
Main <-- MazeExplorer
else
Main -> MazeExplorer: PathValidation(newPath)
Main <-- MazeExplorer
deactivate MazeExplorer
end


Main -> MazeExplorer
alt 
MazeExplorer -> MazeSolver: RightHandSolver(maze)
activate MazeSolver

else
MazeExplorer -> MazeSolver: MazeBFSSolver(maze)

else
MazeExplorer -> MazeSolver: TremauxSolver(maze)

deactivate MazeSolver  
end
MazeSolver --> Main

@enduml